# Generated by Django 5.0 on 2023-12-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="Name")),
                ("password", models.TextField(default="Password")),
                ("document_id", models.IntegerField(default="No_ID")),
            ],
        ),
        migrations.CreateModel(
            name="Explorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="NameE")),
                ("password", models.TextField(default="PasswordE")),
            ],
        ),
        migrations.CreateModel(
            name="SystemChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("planet_amount", models.IntegerField()),
                (
                    "documented_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.documenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanetChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("habitat_rating", models.IntegerField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "documented_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.documenter",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.systemchart",
                    ),
                ),
            ],
        ),
    ]
