# Generated by Django 5.0 on 2023-12-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenter",
            name="document_id",
            field=models.IntegerField(default="No"),
        ),
    ]
