# Generated by Django 5.0 on 2024-01-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetchart",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="planetchart",
            name="habitat_rating",
            field=models.CharField(
                choices=[
                    (10, 10),
                    (9, 9),
                    (8, 8),
                    (7, 7),
                    (6, 6),
                    (5, 5),
                    (4, 4),
                    (3, 3),
                    (2, 2),
                    (1, 1),
                ],
                default=5,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="planetchart",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="planetchart",
            name="system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.systemchart",
            ),
        ),
    ]
