# Generated by Django 5.0 on 2024-01-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_planetchart_documented_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemchart",
            name="documented_by",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
