# Generated by Django 5.0 on 2023-12-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_documenter_password_repeat_alter_documenter_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorer",
            name="password_repeat",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="explorer",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
