# Generated by Django 4.2.7 on 2024-01-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_systemchart_documented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetchart',
            name='habitat_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='systemchart',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
