# Generated by Django 4.2.7 on 2024-01-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_planetchart_habitat_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemchart',
            name='star_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
