# Generated by Django 4.2.7 on 2024-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_systemchart_star_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetchart',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='systemchart',
            name='star_type',
            field=models.CharField(choices=[('Yellow Dwarf Star', 'Yellow Dwarf Star'), ('Red Dwarf Star', 'Red Dwarf Star'), ('White Dwarf Star', 'White Dwarf Star'), ('Brown Dwarf Star', 'Brown Dwarf Star'), ('Red Giant Star', 'Red Giant Star'), ('Blue Giant Star', 'Blue Giant Star'), ('Red Supergiant Star', 'Red Supergiant Star')], max_length=50, null=True),
        ),
    ]
